// Defines route constants to keep navigation paths consistent.
export const ROUTES = {
  home: "/",
  login: "/login",
  logout: "/logout",
  signup: "/signup",
  findId: "/find-id",
  forgotPassword: "/forgot-password",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  trends: "/trends",
  trendingItems: "/shop",
  recommendations: "/recommendations",
  favorites: "/favorites",
  saved: "/favorites",
  productionBoard: "/production-board",
  calendar: "/calendar",
  growthReport: "/growth-report",
  profile: "/profile",
  admin: "/admin",
} as const;
